SELECT NOW(), CURDATE(), CURTIME();	-- NOW() FUNCTION IS USED TO SHOW BOTH CURRENT DATE,TIME
SELECT YEAR(NOW()) ,MONTH(NOW()), DAY(NOW()), HOUR(NOW()), MINUTE(NOW()), SECOND(NOW());		-- EXTRACTING FROM NOW()	-- GIVES INTEGER VALUE
SELECT DAYNAME(NOW()), MONTHNAME(NOW());	-- GIVES STRING VALUE
SELECT EXTRACT(YEAR FROM NOW());	-- 2020		-- WORKING IS SAME AS THE ABOVE FUNCTIONS	-- IT SHOULD BE USED IF WE WANT TO PORT TO OTHER DBMS.
SELECT EXTRACT(MONTH FROM NOW());
SELECT EXTRACT(DAY FROM NOW());

USE sql_store;
SELECT *
FROM orders
-- WHERE order_date >= '2020-01-01'
WHERE YEAR(order_date) = YEAR(NOW());	-- THE ABOVE COMMENTED QUERY IS REPLACED BY THIS.